default_language_version:
  node: 16.0.0
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1' # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        args:
          - --fix
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        language: node
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args:
          - --fix
        entry: bash -c "npm run lint -- --fix"
        additional_dependencies:
          - next@13.0.0
          - eslint@8.34.0
          - eslint-config-next@13.0.0
          - eslint-plugin-unused-imports@2.0.0
