default_language_version:
    node: 16.0.0
repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v2.7.1' # Use the sha or tag you want to point at
      hooks:
          - id: prettier
