default_language_version:
    node: 16.0.0
repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v2.7.1' # Use the sha or tag you want to point at
      hooks:
          - id: prettier
            exclude: ^docs/
    # - repo: https://github.com/pre-commit/mirrors-eslint
    #   rev: 'v8.19.0' # Use the sha / tag you want to point at
    #   hooks:
    #       - id: eslint
    #         files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
    #         types: [file]
    #         exclude: ^docs/
    #         args:
    #             - --fix
    #         additional_dependencies:
    #             - eslint-config-next@12.2.2
    #             - eslint-plugin-unused-imports@2.0.0
