/* eslint-disable unused-imports/no-unused-vars */
export enum Tag {
    ComputeShader = 'Compute Shader',
    Cg = 'Cg',
    HLSL = 'HLSL',
    Unity = 'Unity',
    ShaderGraph = 'Shader Graph',
    ShaderLab = 'ShaderLab',
    VFXGraph = 'VFX Graph',
    VFX = 'VFX',
    VertexShader = 'Vertex Shader',
    FragmentShader = 'Fragment Shader',
    CSharp = 'C#',
    iOS = 'iOS',
    Android = 'Android',
    MobileGame = 'Mobile Game',
    SurfaceShader = 'Surface Shader',
    Lighting = 'Lighting',
    BuiltInRP = 'Built-in RP',
    URP = 'URP',
    HDRP = 'HDRP',
    Tessellation = 'Tessellation',
    _3DModeling = '3D Modeling',
    Animation = 'Animation',
    Blender = 'Blender',
    UI = 'UI',
    ParticleSystem = 'Particle System',
    Material = 'Material',
    MaterialFunction = 'MaterialFunction',
    UnrealEngine = 'Unreal Engine',
    Shader = 'Shader'
}
