/* eslint-disable unused-imports/no-unused-vars */
export enum Tag {
    Cg = 'Cg',
    HLSL = 'HLSL',
    Unity = 'Unity',
    ShaderGraph = 'Shader Graph',
    ShaderLab = 'ShaderLab',
    VFXGraph = 'VFX Graph',
    VFX = 'VFX',
    VertexShader = 'Vertex Shader',
    FragmentShader = 'Fragment Shader',
    CSharp = 'C#',
    iOS = 'iOS',
    Android = 'Android',
    MobileGame = 'Mobile Game',
    SurfaceShader = 'Surface Shader',
    Lighting = 'Lighting',
    BuiltInRP = 'Built-in RP',
    URP = 'URP',
    HDRP = 'HDRP',
    Tessellation = 'Tessellation',
}
